### ISSUE TITLE
check-secrets-action failed 

### ISSUE THREAD

**Issue by jonlipsky** [githubtraining/lab-use-secrets#11]
When I tried to complete the exercise, the check-secrets-failed to run when running the workflow.

![image](https://user-images.githubusercontent.com/1466386/119581699-e96e2600-bd77-11eb-902b-db92f8bb252c.png)

**Comment by jonlipsky** [comment]
@hectorsector @mattdavis0351 I have given you both access to the private repo that I created from the template.

**Comment by mattdavis0351** [comment]
This bug happened when we renamed the repo.  I ended up compiling the `dist/index.js` file without dependencies like `@actions/core` on my local machine.  

Since we ignore `node_modules` when we renamed and I cloned the newly named repo, I ended up without a local copy of the necessary libraries.  That cause a missing dependency when I compiled.  

Fixed in #13 and closing this as a result.

@jonlipsky to try again please create a new repo using this as a template to ensure you get the proper version of the action 😄
