### ISSUE TITLE
Change feedback message displayed by troubleshooting workflow

### ISSUE THREAD

**Issue by lucie-docs** [githubtraining/lab-use-secrets#16]
This is an issue triggered by https://github.com/github/programs-forge/issues/159#issuecomment-850337391 

![119911013-b82b5c80-bf15-11eb-8feb-f2f838262f78](https://user-images.githubusercontent.com/40564413/119991056-57f5f280-bfc9-11eb-9cd3-f266478f6b10.png)

The message displayed by the troubleshooting workflow is confusing for the learner. The workflow passed, yet the learner is still invited to check documentation if they are stuck. 

I think the troubleshooting workflow should display the same message as the grading workflow to indicate to the learner that they passed or failed the exercise. I don't know how to do that though.

Thoughts? @hectorsector @mattdavis0351

**Comment by hectorsector** [comment]
@lucie-docs here it is: 

https://github.com/githubtraining/exercise-use-secrets/blob/d7b6b748a62faeefef182eb1c3abd80c703ee3b4/.github/workflows/grading.yml#L22

**Comment by hectorsector** [comment]
@mattdavis0351 can we surface the troubleshooting feedback in an annotation or expand the step in the workflow?

**Comment by mattdavis0351** [comment]
## Workflow run status

>The workflow passed, yet the learner is still invited to check documentation if they are stuck.

@lucie-docs This is a GitHub Actions thing.  The workflow success indication is because the troubleshooting step finished successfully.  If the troubleshooter broke then we would see a failure for the workflow.  

I understand that it's slightly confusing, but you have to decouple green=good and red=bad and turn it into no-problems=green and problems=red.

This is something that we have limited control over.  We can force a failure status, but that would get confusing as well since we may think something is broken with the troubleshooter, when in fact there was nothing wrong at all.

Another reason this can easily be a problem is when we integrate automated testing into the exercises that warrant it.  If a workflow step is failing, we won't be able to automate release processes and other tasks that we have in mind to automate.  They all rely on successful runs, or green statuses.

I hope that helps, unfortunately there is confusion either way, so I'm leaning on what makes sense from the GitHub Actions feature perspective.  

What I would hope is that the learner knows enough about Actions if they are adding secrets to a workflow to understand that green simply means a step in the workflow didn't fail and it returned a 0 exit code.  **Especially since they are coming to this exercise AFTER extensively learning about Actions**.

## So you want annotations huh?

@hectorsector From my understanding, we only get annotations if we throw an error.  I can't justify throwing an error when there is no error, if that makes sense.  We are limited to these workflow commands:

![image](https://user-images.githubusercontent.com/38021615/120029786-67664300-bfab-11eb-9824-90357c7da95b.png)

And so far the only one I've found that sets an annotation is the core.setFailed and core.error commands/methods.

Neither of these make sense considering the workflow step, nor the learner, is creating an error or achieving failure.  They are simply asking for troubleshooting help, which we are successfully giving them.

## We just aren't there yet... but could be if we had more time!


The current `echo` was supposed to be placeholder which we planned to expand further as these exercises matured.  We haven't gotten to that point yet, and I'm not sure we want to use LG for troubleshooting help, although nothing stops us from doing so.

I faintly remember a discussion of doing this, but we decided against is since we would most likely throw it in an issue and we would be recreating LL in a sense.  

One thing to keep in mind is that the troubleshooting step has **no access** to what the learner has done.  It cannot communicate with the `use-secrets.yml` workflow.  

What **could, maybe, possibly** happen is that the `use-secrets-action` matures to handle not just creating a grading payload, but also can be called by the troubleshooter to help provide more information.  BUT, and it's a huge BUT, the `use-secrets-action` would still **not have access** to the learners secret.  

If we wanted it to have access to that secret we would be asking the learner to do one of two things:

- Make a change to the `grading.yml`, which we don't want them to do, hence the `use-secrets.yml` workflow
- Pass the secret into the `workflow_dispatch` event when they run the troubleshooter.  This is much more feasible to do, however will require a large effort to make the `use-secrets-action` more robust to handle being used in two different contexts.  (We would also be providing them damn near the same information they get when they run the `use-secrets.yml` workflow, making this redundant)

>I think the troubleshooting workflow should display the same message as the grading workflow to indicate to the learner that they passed or failed the exercise. I don't know how to do that though.

In my opinion we shouldn't grade twice simply for the sake of troubleshooting.  Troubleshooting was mean to be help if something with the exercise was wrong, whereas grading feedback is meant to say if the learner is doing something correctly or incorrectly.

**Comment by lucie-docs** [comment]
@mattdavis0351 I mean I just wanted to change the message there so it's more user-friendly. Something like "You passed the exercise!" would be better than redirecting the user to the docs in terms of UX. I'm guessing that the user wouldn't go dig into the log if the workflow succeeds anyways, but I thought since we're gathering user feedback to polish the whole thing, we might as well do that too? But if that makes things more complicated when we start building other exercises, I'm totally fine with not changing anything! 😅

**Comment by mattdavis0351** [comment]
@lucie-docs I feel like there is a misunderstanding of what is taking place in the `grading.yml` workflow.

There are 2, unrelated, steps in this workflow.

- The actual grading
- Troubleshooting help

And they are each triggered differently.

The actual grading takes place from the specific learner action we are expecting them to take whereas the troubleshooting help only runs if the learner specifically asks it to run.

So in 90% of situations, the troubleshooting step will never run, because the learner will be performing the task that triggers the actual grading step.

So to print that they did something correct in the troubleshooter is not really its purpose.  We tell them they are correct in the grading step:
![image](https://user-images.githubusercontent.com/38021615/120037486-9209c900-bfb6-11eb-971d-0dacb6e2fa2e.png)


There is no possible way the troubleshooting step would know if they were correct or incorrect.  If they are running the troubleshooter they are neither correct or incorrect.  Our intent was to give them a step they could run to ask for help in the event they were super stuck, or the exercise was broken.  Hence the direction to official documentation. 

If I'm stuck, the best place to look to get unstuck is official docs.

---

Edit:

What I'm trying to explain is that there is no separate workflow for grading and troubleshooting.  They are the exact same workflow, it just behaves differently based on if it's grading or if it's providing troubleshooting feedback.  Which are two unrelated tasks but we wanted to keep the number of workflows in the repo to a minimum as well as make sure these things took place in a workflow that the learner shouldn't edit.

Here is the code in the grading workflow that may help with this explanation:
```
name: Grading workflow
  on:  
    repository_dispatch:    
      types: ["grading"]  

    workflow_dispatch:
```

As you can see, there are two triggers, `repository_dispatch` and `worfklow_dispatch`.  This first, `repository_dispatch` is responsible for letting the learner know if they are correct or incorrect, which is what is in the screenshot above.  The other, `workflow_dispatch` is a **manual** trigger that displays the message in the opening comment to this issue.

The way it works from a more technical level is this:

```
grade-learner:    
    if: github.event_name == 'repository_dispatch'
        <run some grading steps to check if incorrect or correct and provide feedback>


troubleshoot-activity:    
    if: github.event_name == 'workflow_dispatch'
         <Provide helpful docs on how to get started or how to fix broken exercise>
```

The key is the `if` statements.  They let us filter what behavior happens based on which event triggered the `grading.yml` workflow.


This setup of having 2 triggers, 1 automatic and 1 manual, in the `grading.yml` workflow is followed in all of the exercises we are creating.

**Comment by lucie-docs** [comment]
Thanks for the explanation @mattdavis0351! So I think this is what is in the instruction that is misleading: "If the grading workflow does not automatically run after you complete the instructions, run the troubleshooter: in the Actions tab select the Grading workflow, click Run workflow, select the appropriate branch, and click the Run workflow button." 
I had understood that the troubleshooter was here if there was a technical problem with the grading workflow but in fact the learner can use it to get pointers on what they might have done wrong in the exercise. 
I have an idea of something to add in the instructions to set the learner's expectation, will open PR!

**Comment by mattdavis0351** [comment]
@lucie-docs I agree that we should change the wording on the instructions around the troubleshooter for this exercise.

>but in fact the learner can use it to get pointers on what they might have done wrong in the exercise.

I'm not sure if I'm interpreting this correctly, but the way I'm reading it is that there is some hope that the troubleshooter can help the learner figure out where they are wrong. 

That's just not possible with this exercise to do efficiently due to how Actions and the `GITHUB_TOKEN` secret work.  The only two ways would be 
- having the learner edit the `grading.yml`, which we've decided is not a good practice.
- running the local action in this step... but that requires the leaner supply a secret, and we end up back to the first bullet point.

**Comment by lucie-docs** [comment]
@mattdavis0351 thanks for the additional explanation! Ok, opening PR.
